# Generated by Django 2.1.5 on 2019-02-19 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('is_new', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, help_text='Tell us a bit about yourself.', max_length=1500)),
                ('date_of_birth', models.DateField(blank=True, help_text='Please use one of the following formats: YYYY-MM-DD, MM/DD/YYYY, MM/DD/YY', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
